# -*- coding: utf-8 -*-
"""AI-Query-Tube.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MDvS4BCMl5g_wHACYThee8ls4o3cZABc
"""





df.to_csv("youtube_metadata.csv", index=False)
print(df)

url = "https://www.googleapis.com/youtube/v3/search"
params = {
    "key": "AIzaSyClp4BGIhErUnzC4phSk_EhW-8vUGhOJ58",
    "channelId": "UC8butISFwT-Wl7EV0hUK0BQ",
    "part": "snippet,id",
    "order": "date",
    "maxResults": 50
}

response = requests.get(url, params=params).json()

videos = []
for item in response["items"]:
    if "videoId" in item["id"]:
        video_id = item["id"]["videoId"]
        title = item["snippet"]["title"]
        published = item["snippet"]["publishedAt"]
        videos.append([video_id, title, published])

df = pd.DataFrame(videos, columns=["video_id", "title", "published_date"])
df.head()

import requests
import pandas as pd

API_KEY = "AIzaSyClp4BGIhErUnzC4phSk_EhW-8vUGhOJ58"
CHANNEL_ID = "UC8butISFwT-Wl7EV0hUK0BQ"

!pip install requests pandas