# -*- coding: utf-8 -*-
"""AI-Query-Tube.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MDvS4BCMl5g_wHACYThee8ls4o3cZABc
"""

!pip install youtube-transcript-api

df.to_csv("youtube_metadata.csv", index=False)
print(df)

url = "https://www.googleapis.com/youtube/v3/search"
params = {
    "key": "AIzaSyClp4BGIhErUnzC4phSk_EhW-8vUGhOJ58",
    "channelId": "UC8butISFwT-Wl7EV0hUK0BQ",
    "part": "snippet,id",
    "order": "date",
    "maxResults": 50
}

response = requests.get(url, params=params).json()

videos = []
for item in response["items"]:
    if "videoId" in item["id"]:
        video_id = item["id"]["videoId"]
        title = item["snippet"]["title"]
        published = item["snippet"]["publishedAt"]
        videos.append([video_id, title, published])

df = pd.DataFrame(videos, columns=["video_id", "title", "published_date"])
df.head()

import requests
import pandas as pd

API_KEY = "AIzaSyClp4BGIhErUnzC4phSk_EhW-8vUGhOJ58"
CHANNEL_ID = "UC8butISFwT-Wl7EV0hUK0BQ"

!pip install requests pandas

# Commented out IPython magic to ensure Python compatibility.
# NEXT WEEK
# %pip install youtube-transcript-api sentence-transformers tf-keras

import os
import sys
import time
import requests
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import TranscriptsDisabled, NoTranscriptFound, VideoUnavailable
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

!pip install youtube-transcript-api

!pip install yt-dlp

from youtube_transcript_api import YouTubeTranscriptApi

transcripts = []
for vid in df["video_id"]:
    try:
        transcript = YouTubeTranscriptApi.get_transcript(vid)
        text = " ".join([t["text"] for t in transcript])
        transcripts.append(text)
    except:
        transcripts.append(None)  # if transcript not available

df["transcript"] = transcripts
df.head()

print(df)

missing = df[df["transcript"].isnull()]
print("Videos without transcripts:", len(missing))

!pip install sentence-transformers
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

df["text_for_embedding"] = df["title"] + " " + df["transcript"].fillna("")
corpus = df["text_for_embedding"].tolist()

df["embedding"] = df["text_for_embedding"].apply(lambda x: model.encode(x))

from sklearn.metrics.pairwise import cosine_similarity

query = "python basics"
query_embedding = model.encode(query)

scores = cosine_similarity([query_embedding], list(df["embedding"]))
top_idx = scores[0].argsort()[-7:][::-1]  # Top 5 results
df.iloc[top_idx][["title","video_id"]]

results = df.iloc[top_idx][["title", "video_id"]].copy()
results["score"] = scores[0][top_idx]
print(results)