# -*- coding: utf-8 -*-
"""Milestone1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e3ckD_lmofjeHGr7Wsx_W2krNDX5bP3p
"""

!pip install requests pandas

import requests
import pandas as pd

API_KEY = "AIzaSyDAp05ZTQIKhpHw6-mmeTKDGIBub6kK2-8"
CHANNEL_ID = "UCsT0YIqwnpJCM-mx7-gSA4Q"

url = "https://www.googleapis.com/youtube/v3/search"

params = {
    "key": API_KEY,
    "channelId": CHANNEL_ID,
    "part": "snippet,id",
    "order": "date",
    "maxResults": 50,
    "type": "video"
}

response = requests.get(url, params=params).json()

videos = []

for item in response.get("items", []):
    if "videoId" in item["id"]:
        videos.append([
            item["id"]["videoId"],
            item["snippet"]["title"],
            item["snippet"]["publishedAt"]
        ])

df = pd.DataFrame(videos, columns=["video_id", "title", "published_date"])
df["published_date"] = pd.to_datetime(df["published_date"])

df.to_csv("youtube latest videos.csv", index=False)
print("File saved successfully!")

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("youtube latest videos.csv")
df.head()

df.shape

df.info()

df.isnull().sum()

df["video_id"].nunique(), len(df)

df["title"].nunique(), len(df)

df["published_date"] = pd.to_datetime(df["published_date"])

df["year"] = df["published_date"].dt.year
videos_per_year = df["year"].value_counts().sort_index()
videos_per_year

plt.figure()
videos_per_year.plot(kind="line", marker="o")
plt.xlabel("Year")
plt.ylabel("Number of Videos")
plt.title("YouTube Video Publish Trend (TEDx Talks)")
plt.show()

df["title_length"] = df["title"].apply(len)
df["title_length"].describe()

plt.figure()
df["title_length"].plot(kind="hist", bins=10)
plt.xlabel("Title Length")
plt.title("Distribution of Video Title Lengths")
plt.show()

df_cleaned = df[["video_id", "title", "published_date"]]
df_cleaned.to_csv("youtube_metadata_cleaned.csv", index=False)